"""initial_schema

Revision ID: 3e1fe4d03ee4
Revises: 
Create Date: 2026-06-19 23:02:37.128394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '3e1fe4d03ee4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension (must exist before VECTOR columns)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('dek', sa.Text(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('body_final_md', sa.Text(), nullable=True),
    sa.Column('envelope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claims_used', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('fact_pass_rate', sa.Float(), nullable=True),
    sa.Column('similarity_max', sa.Float(), nullable=True),
    sa.Column('review_path', sa.Text(), server_default=sa.text("'auto_gated'"), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'drafted'"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # HNSW index on article embeddings for fast cosine-similarity search
    op.execute(
        "CREATE INDEX IF NOT EXISTS articles_embedding_hnsw "
        "ON articles USING hnsw (embedding vector_cosine_ops)"
    )
    # Atomic budget reservation function (fixes O-C3)
    op.execute("""
        CREATE OR REPLACE FUNCTION reserve_budget(p_day DATE, p_amount NUMERIC)
        RETURNS BOOLEAN LANGUAGE plpgsql AS $$
        DECLARE ok BOOLEAN;
        BEGIN
          UPDATE budget_day SET reserved_usd = reserved_usd + p_amount
           WHERE day = p_day AND reserved_usd + p_amount <= ceiling_usd
          RETURNING TRUE INTO ok;
          RETURN COALESCE(ok, FALSE);
        END $$;
    """)
    op.create_table('budget_day',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('reserved_usd', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('actual_usd', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('ceiling_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('escalations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('escalation_cap', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('claims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('supporting_span', sa.Text(), nullable=False),
    sa.Column('span_sha256', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entailment_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=True),
    sa.Column('judge_kind', sa.Text(), nullable=True),
    sa.Column('judge_model', sa.Text(), nullable=True),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weighted', sa.Float(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_type', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), server_default=sa.text("'raw'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('source_health',
    sa.Column('source_class', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('items_seen', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('source_class', 'window_start')
    )
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_class', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('license_flag', sa.Text(), nullable=True),
    sa.Column('scrape_allowed', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('url_hash', sa.Text(), nullable=False),
    sa.Column('content_simhash', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_class', 'external_id')
    )
    op.create_table('spend_ledger',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('in_tokens', sa.Integer(), nullable=True),
    sa.Column('out_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_state',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_state')
    op.drop_table('spend_ledger')
    op.drop_table('sources')
    op.drop_table('source_health')
    op.drop_table('runs')
    op.drop_table('evals')
    op.drop_table('claims')
    op.drop_table('budget_day')
    op.drop_table('articles')
    op.execute("DROP INDEX IF EXISTS articles_embedding_hnsw")
    op.execute("DROP FUNCTION IF EXISTS reserve_budget(DATE, NUMERIC)")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
